#include <stdio.h>  //Printf() function
#include <stdlib.h> //Exit() function

#include <string.h> //String functions

#include "log.h" //Printing to the console

/**
 * analyser.c
 * This file concerns the semantic analysis of the generated code after translation. Specifically, it checks if jumps like 'fuck go back' were
 * defined without their respective jump marker, 'upgrade' in this case.
 */


/**
 * Opens the opcode-file generated by the translator and analyses it for semantic errors
 */
void startSemanticAnalysis() {
    FILE *analyzerPTR = fopen("opcodes", "r");

    int upgradeMarkerDefined = 0; //Is set to 1 if 'upgrade' is defined somewhere. That way, the compiler can check if it is defined multiple times or 'fuck go back' is used without it
    int upgradeJumpDefined = 0; //Is set to the line in which 'fuck go back' is in. This is so that the jump marker can be defined under that line without throwing an error

    int pictureMarkerDefined = 0; //Is set to 1 if 'they're the same picture' is defined somewhere. That way, the compiler can check if it is defined multiple times or 'fuck go back' is used without it
    int pictureJumpDefined = 0; //Is set to the line in which 'coporate needs you to find...' is in. This is so that the jump marker can be defined under that line without throwing an error

    int perfectlyBalanced = 0; //Is set to 1 if 'perfectly balanced as all things should be' is defined somewhere

    char line[5];
    int lineNum = 1;
    while(fgets(line, 5, analyzerPTR) != NULL) {
        int opcode = (int) strtol(line, (char **) NULL, 10);

        switch (opcode){
            case 2: //'Upgrade'
                printDebugMessage("Opcode is 'upgrade'-marker", line);
                if(upgradeMarkerDefined == 0) upgradeMarkerDefined = lineNum;
                else {
                    printSemanticErrorWithExtraLineNumber("'upgrade' jump marker can only be defined once", lineNum, upgradeJumpDefined);
                }
                break;
            case 3: //'fuck go back'
                printDebugMessage("Opcode is 'fuck go back'", line);
                upgradeJumpDefined = lineNum;
                break;
            case 9: //'they're the same picture'
                printDebugMessage("Opcode is 'they're the same picture'-marker", line);
                if(pictureMarkerDefined == 0) pictureMarkerDefined = lineNum;
                else {
                    printSemanticErrorWithExtraLineNumber("'they're the same picture' jump marker can only be defined once", lineNum, pictureMarkerDefined);
                }
                break;    
            case 10: //'coporate needs you to find the difference...'
                printDebugMessage("Opcode is compare-statement", line);
                pictureJumpDefined = lineNum;
                break;    
            default:
                printDebugMessage("Opcode is not relevant, moving on...", line);
                break;
        }
        lineNum++;
    }
    fclose(analyzerPTR);

    //Now that we traversed the entire file, we still need to check if jumps were defined without markers
    if(pictureJumpDefined != 0 && pictureMarkerDefined == 0) {
        printSemanticError("'coporate needs you to find the difference between ...' was used, but 'they're the same picture' wasn't defined anywhere", lineNum);
    } else if(upgradeJumpDefined != 0 && upgradeMarkerDefined == 0) {
        printSemanticError("'fuck go back' was used, but no 'upgrade' jump marker was found", lineNum);
    }
}  