#ifndef ANALYSER_H
#define ANALYSER_H

#include <stdio.h>  //Printf() function
#include <stdlib.h> //Exit() function

#include <string.h> //String functions

/**
 * Opens the opcode-file generated by the translator and analyses it for semantic errors
 * @param opcodes an array containing the opcode of each line
 * @param lineCount the number of lines
 */
void startSemanticAnalysis(int opcodes[], int lineCount);

#endif