#ifndef ANALYSE_H
#define ANALYSE_H

#include <stdio.h>  //Printf() function
#include <stdlib.h> //Exit() function

#include <string.h> //String functions

/**
 * Opens the opcode-file generated by the translator and analyses it for semantic errors
 */
void startSemanticAnalysis();

#endif