#include <stdio.h>  //Printf() function
#include <stdlib.h> //Exit() function

#include <string.h> //String functions

#include "log.h" //Printing to the console

/**
 * analyser.c
 * This file concerns the semantic analysis of the generated code after translation. Specifically, it checks if jumps like 'fuck go back' were
 * defined without their respective jump marker, 'upgrade' in this case.
 */


/**
 * Opens the opcode-file generated by the translator and analyses it for semantic errors
 * @param opcodes an array containing the opcode of each line
 * @param lineCount the number of lines
 */
void startSemanticAnalysis(int opcodes[], int lineCount) {
    int upgradeMarkerDefined = 0; //Is set to the line in which 'upgrade' is defined. That way, the compiler can check if it is defined multiple times or 'fuck go back' is used without it
    int upgradeJumpDefined = 0; //Is set to the line in which 'fuck go back' is in. This is so that the jump marker can be defined under that line without throwing an error

    int pictureMarkerDefined = 0; //Is set to to the line in which 'they're the same picture' is defined. That way, the compiler can check if it is defined multiple times or 'fuck go back' is used without it
    int pictureJumpDefined = 0; //Is set to the line in which 'coporate needs you to find...' is in. This is so that the jump marker can be defined under that line without throwing an error

    int perfectlyBalanced = 0; //Is set to 1 if 'perfectly balanced as all things should be' is defined somewhere

    for(int i = 0; i < lineCount; i++) {
        int opcode = opcodes[i];
        int lineNum = i + 1;
        printDebugMessageWithNumber("\nOpcode is", opcode);

        switch (opcode){
            case 2: //'Upgrade'
                printDebugMessage("Opcode is 'upgrade'-marker", "");
                if(upgradeMarkerDefined == 0) upgradeMarkerDefined = lineNum;
                else {
                    printSemanticErrorWithExtraLineNumber("'upgrade' jump marker can only be defined once", lineNum, upgradeJumpDefined);
                }
                break;
            case 3: //'fuck go back'
                printDebugMessage("Opcode is 'fuck go back'", "");
                upgradeJumpDefined = lineNum;
                break;
            case 9: //'they're the same picture'
                printDebugMessage("Opcode is 'they're the same picture'-marker", "");
                if(pictureMarkerDefined == 0) pictureMarkerDefined = lineNum;
                else {
                    printSemanticErrorWithExtraLineNumber("'they're the same picture' jump marker can only be defined once", lineNum, pictureMarkerDefined);
                }
                break;    
            case 10: //'coporate needs you to find the difference...'
                printDebugMessage("Opcode is compare-statement", "");
                pictureJumpDefined = lineNum;
                break;    
            default:
                printDebugMessage("Opcode is not relevant, moving on...", "");
                break;
        }
        lineNum++;
    }

    //Now that we traversed the entire file, we still need to check if jumps were defined without markers
    if(pictureJumpDefined != 0 && pictureMarkerDefined == 0) {
        printSemanticError("'coporate needs you to find the difference between ...' was used, but 'they're the same picture' wasn't defined anywhere", pictureJumpDefined);
    } else if(upgradeJumpDefined != 0 && upgradeMarkerDefined == 0) {
        printSemanticError("'fuck go back' was used, but no 'upgrade' jump marker was found", upgradeJumpDefined);
    }
    printInfoMessage("Semantic analysis done, no issues found");
}  